### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by kingcc** [Aploium/WebQQ_API#1]
你好啊赵同学
1.  为什么不使用标准的版本号命名法呢 `<major | minor | patch>`
2.  看了你的`resume`和`resp`感觉想法和技术都很棒，祝愿你能找到一份理想的实习

**Comment by aploium** [comment]
这个是很早的时候随便写的。。qwq
后来的zmirror是用语义版本的，现在还处于0.x的开发当中

**Comment by aploium** [comment]
补一句谢谢:smile:
